spring:
#  main:
#    web-environment: false
  datasource:
    url: jdbc:h2:mem:TEST;MVCC=true;DB_CLOSE_DELAY=-1;MODE=Oracle
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
    initialize: true
    enabled: true
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop

logging:
  file: log/crawler-rendafixa.log
  pattern:
    console: "%d [%-5level] [%thread] [%c{0}] %message %n"
    file: "%d [%-5level] [%thread] [%c{0}] %message %n"
  level:
    org.springframework: INFO
    br.com.clubedoporquinho: DEBUG

waitForBackgroundJavaScript: 10000
