logging:
  file: log/crawler-rendafixa.log
  pattern:
    console: "%d [%-5level] [%thread] [%c{0}] %message %n"
    file: "%d [%-5level] [%thread] [%c{0}] %message %n"
  level:
    org.springframework: INFO
    br.com.clubedoporquinho: TRACE
waitForBackgroundJavaScript: 10000
